version: "3"
services:
  database:
    image: postgres:latest
    container_name: biznesowy-postgres-db
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: BiznesProjekt